### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by Basilakis** [rubengc/cmb2-field-order#2]
Hello,

What is the usage example of that plugin / script, would it be possible to let us know?

Thank you

**Comment by rubengc** [comment]
I always add an example in the readme file

Just include the main file and setup a field with the new type

**Comment by Basilakis** [comment]
@rubengc You have no example, on how yo use the field for the front end call.
The array for the configuration exists, but not the front end field.

Could you please be kind enough, to let us now how we can use for the front end also, please?

Thank you.
